version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      HOST: localhost
      USER: root
      PASSWORD: password
      DATABASE: task1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db