version: '3'

services:

  app:
    image: app
    build: .
    environment:
      - HOST=db
      - USER=root
      - PASSWORD=password
      - DATABASE=task1
    depends_on:
      - db
    networks:
      - app-network
    
    ports:
      - 5000:5000

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=task1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge